osx_image: xcode8.1
language: objective-c
cache:
  - bundler
  - cocoapods
branches:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem install bundler
  - bundle install && brew bundle
script:
  - bundle exec fastlane travis_framework_tests
after_success:
  - bundle exec fastlane travis_framework_after_success_action
